DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
  ID_PRODUCT INTEGER PRIMARY KEY,
  NAME VARCHAR(50),
  PRICE DOUBLE,  
  CATEGORY VARCHAR(50),
  QUANTITY VARCHAR(50)
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
  ID_CUSTOMER INTEGER PRIMARY KEY,
  NAME VARCHAR(250),
  MAIL VARCHAR(250),
  PHONE VARCHAR(9)
);
