INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(1,'ENSALADA DE ESPINACAS',1.65,'PRINCIPAL','100g');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(2,'TORTELINI ALLA CARBONARA',1.30,'PRINCIPAL','100g');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(3,'POLLO AL CURRY',1.55,'PRINCIPAL','100g');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(4,'ARROZ CON VERDURAS',1.55,'PRINCIPAL','100g');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(5,'ROLLO DE PRIMAVERA',2.00,'PRINCIPAL','ud');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(6,'CARNE ESTOFADA',2.15,'PRINCIPAL','100g');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(7,'AGUA',1.20,'DRINK','ud');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(8,'ZUMO DE NARANJA',2.00,'DRINK','ud');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(9,'MANZANA',2.00,'DESSERT','ud');
INSERT INTO PRODUCT (ID_PRODUCT,NAME,PRICE,CATEGORY,QUANTITY) values(10,'TARTA DE QUESO',2.50,'DESSERT','ud');


INSERT INTO CUSTOMER (ID_CUSTOMER,NAME,MAIL,PHONE) values(1,'ANGEL ARROJO','angelarrojo@gmail.com','687754285');
